FROM python:3.8

WORKDIR /api

COPY / /api
COPY pyproject.toml /api/pyproject.toml

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

CMD ["poetry", "shell"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
